version: '3'

services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    networks:
      - americas-technology-network
    container_name: database-americas-technology
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_americas_technology
    ports:
      - "3306:3306"

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    networks:
      - americas-technology-network
    container_name: auth-service-americas-technology
    env_file:
      - .env  # Specify the path to your .env file
    ports:
      - "8082:8082"
    depends_on:
      - db

  crud-users:
    build:
      context: ./crud-users
      dockerfile: Dockerfile
    networks:
      - americas-technology-network
    container_name: crud-users-americas-technology
    env_file:
      - .env  # Specify the path to your .env file
    ports:
      - "8080:8080"
    depends_on:
      - db

  order-service:
    build:
      context: ./order-service
      dockerfile: Dockerfile
    networks:
      - americas-technology-network
    container_name: order-service-americas-technology
    env_file:
      - .env  # Specify the path to your .env file
    ports:
      - "8081:8081"
    depends_on:
      - db

networks:
  americas-technology-network:
    driver: bridge
