# ./docker-compose.yml

version: '3'

services:
  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    networks:
      - americas-technology-network
    container_name: database-americas-technology
    env_file:
      - .env
    ports:
      - "3306:3306"

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    networks:
      - americas-technology-network
    container_name: auth-service-americas-technology
    env_file:
      - .env
    ports:
      - "8082:8082"
    depends_on:
      - database

  crud-users:
    build:
      context: ./crud-users
      dockerfile: Dockerfile
    networks:
      - americas-technology-network
    container_name: crud-users-americas-technology
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - database
      - auth-service

  order-service:
    build:
      context: ./order-service
      dockerfile: Dockerfile
    networks:
      - americas-technology-network
    container_name: order-service-americas-technology
    env_file:
      - .env
    ports:
      - "8081:8081"
    depends_on:
      - database
      - auth-service

networks:
  americas-technology-network:
    driver: bridge
