# ./db/Dockerfile
# Use an official MySQL runtime as a parent image
FROM mysql

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Expose port 3306 to allow external connections to the database
EXPOSE 3306
