# Use an official Golang runtime as a parent image
FROM golang

# Set the working directory to /crud-users
WORKDIR /crud-users

# Copy the current directory contents into the container at /crud-users
COPY . /crud-users

# Build the crud-users command inside the container
RUN go mod download
RUN go build -o crud-users .

# Run the crud-users command when the container starts
CMD ["./crud-users"]
